### ISSUE TITLE
ULCase bug in InfoStation handling

### ISSUE THREAD

**Issue by David-S-Morgan** [Cosmic-Chatter/Constellation#1]
Hi,

I had an issue with editing an InfoStation component from the control server after creation.  Platform is Ubuntu 22.04 for both control server and client running the InfoStation component.  Using latest Constellation.

I traced the issue to the fact that the Edit option of the dropdown menu is associated with this url:

`http://<<COMPONENT_IP>>:8000/infostation/setup.html?definition=<<UUID>>`

when it should be

`http://<<COMPONENT_IP>>:8000/InfoStation/setup.html?definition=<<UUID>>`

(e.g. "InfoStation" in the URL instead of "infostation").  Note that this probably wouldn't be noticed on a Mac (which I think I saw a comment to the effect that the program is developed on a Mac platform) since the default Mac filesystem is case-insensitive.

The URL is created from, in part, the definition in apps/InfoServer/setup.js:636.  Specifically:

`definition.app = 'infostation'`

However, changing this to 'InfoStation' breaks other things.  I think I've worked around it with the following kludge in control_server/constellation_exhibit.js, starting at line 1448

    if (definition.app === 'infostation' ) {
    dropdownMenu.innerHTML = `
    <a class="dropdown-item" href="${component.getHelperURL() + '/' + definition.app + '.html?standalone=true&definition=' + uuid}" target="_blank">Preview</a>
    <a class="dropdown-item" href="${component.getHelperURL() + '/InfoStation/setup.html?definition=' + uuid}" target="_blank">Edit</a>
    `
    } else {
    dropdownMenu.innerHTML = `
    <a class="dropdown-item" href="${component.getHelperURL() + '/' + definition.app + '.html?standalone=true&definition=' + uuid}" target="_blank">Preview</a>
    <a class="dropdown-item" href="${component.getHelperURL() + '/' + definition.app + '/setup.html?definition=' + uuid}" target="_blank">Edit</a>
    `
    }

No doubt it would be better to normalize the name across the code.

**Comment by forceflow1049** [comment]
Hi @David-S-Morgan, thank you so much for the detailed bug report! I'm happy to share that this bug has already been fixed in Version 5, which will release in a couple of weeks! So has a related bug involving the Word Cloud app.

By the way, we have moved development on Constellation over to a new repo as part of the name change to Exhibitera. You can find the repo [here](https://github.com/Cosmic-Chatter/Exhibitera) and the new website [here](https://exhibitera.org).

**Comment by David-S-Morgan** [comment]
Thanks for the redirect to the new project site! Glad to hear the project is still active -- I thought it seemed pretty quiet around here.
